#!/usr/bin/env node
// scripts/test-build.mjs — Regression test suite for Kalinga Sthapatya build.
// Tests the static site generator against dev/fixtures to ensure zero-dependency,
// accessible, valid markup with no broken classes, double-rendered claims, or missing sections.
//
// Usage:
//   node --test scripts/test-build.mjs       Run tests via Node test runner
//   node scripts/test-build.mjs              Run tests directly
//   node scripts/test-build.mjs --update     Update golden snapshots in test/snapshots/

import test, { describe, it, before, after } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmSync,
  existsSync,
  readdirSync,
  statSync,
} from "node:fs";
import { resolve, join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { loadData } from "./build/lib/data.mjs";
import { createContext } from "./build/lib/context.mjs";
import { siteConfig } from "./build/config.mjs";
import { resetUid, escapeHtml } from "./build/lib/html.mjs";
import { isClaim } from "./build/lib/components.mjs";
import {
  journeyRail,
  journeyStop,
  storyCard,
  passport,
  partsTour,
  videoFacade,
  resolveClaimPath,
  createRenderLedger,
} from "./build/lib/journey.mjs";
import { renderTemple } from "./build/pages/temple.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SNAPSHOTS_DIR = join(ROOT, "test", "snapshots");

const REQUIRED_TEMPLE_CLASSES = [
  "journey-rail",
  "journey-stop",
  "journey-stop__full",
  "story-card",
  "passport",
  "parts-tour",
  "tour-step",
  "journey-frame",
  "video-facade",
  "scale-drawing__wrap",
  "more-to-spot",
  "next-temple-card",
];

// Helper to recursively collect all .html files generated by the build
function getHtmlFiles(dir) {
  const results = [];
  if (!existsSync(dir)) return results;
  for (const item of readdirSync(dir)) {
    const full = join(dir, item);
    if (statSync(full).isDirectory()) {
      results.push(...getHtmlFiles(full));
    } else if (item.endsWith(".html") && item !== "inbox.html") {
      // inbox.html is a standalone local visual-briefs reviewer, not a build page
      results.push(full);
    }
  }
  return results;
}

// Helper to extract claims from an object tree
function extractClaims(obj) {
  const claims = [];
  if (isClaim(obj)) return [obj];
  if (Array.isArray(obj)) {
    obj.forEach((v) => claims.push(...extractClaims(v)));
  } else if (obj && typeof obj === "object") {
    Object.values(obj).forEach((v) => claims.push(...extractClaims(v)));
  }
  return claims;
}

// Build a full-featured journey temple page in-memory using fixture assets and structure
function renderFullJourneyTemple(dataDir = "dev/fixtures") {
  resetUid();
  const data = loadData(resolve(ROOT, dataDir));

  // Add elements required by TEMPLE_TOURS.parasuramesvara
  data.elementsById.set("jagamohana", {
    id: "jagamohana",
    name: "FIXTURE Jagamohana",
    what: { text: "FIXTURE: fake hall description", tier: "established" },
  });
  data.elementsById.set("bada", {
    id: "bada",
    name: "FIXTURE Bada",
    what: { text: "FIXTURE: fake wall description", tier: "established" },
  });
  data.elementsById.set("gandi", {
    id: "gandi",
    name: "FIXTURE Gandi",
    what: { text: "FIXTURE: fake spire description", tier: "established" },
  });

  // Approved build-video and build-sequence frames for howMedia and partsMedia
  data.media.assets.push({
    id: "V-FIX-VID",
    temple_id: "parasuramesvara",
    role: "build-video",
    status: "approved",
    path: "dev/fixtures/assets/test.mp4",
    width: 1280,
    height: 720,
  });
  data.media.assets.push({
    id: "V-FIX-FRAME1",
    temple_id: "parasuramesvara",
    role: "build-sequence",
    order: 1,
    status: "approved",
    path: "dev/fixtures/assets/fixture-hero-a.svg",
    width: 320,
    height: 180,
  });
  data.media.assets.push({
    id: "V-FIX-FRAME2",
    temple_id: "parasuramesvara",
    role: "build-sequence",
    order: 2,
    status: "approved",
    path: "dev/fixtures/assets/fixture-parts-a.svg",
    width: 200,
    height: 260,
  });
  for (const a of data.media.assets) {
    data.mediaById.set(a.id, a);
  }

  const baseTemple = data.temples.temples.find((t) => t.id === "fixture-temple-b");
  const temple = JSON.parse(JSON.stringify(baseTemple));
  temple.id = "parasuramesvara"; // matches TEMPLE_TOURS
  temple.name = "FIXTURE Full Journey Temple";
  temple.page = "temples/parasuramesvara.html";

  // 4 special claims for TEMPLE_TOURS + 1 extra for more-to-spot
  temple.sections.special = [
    { text: "FIXTURE: tour special claim 0", tier: "established" },
    { text: "FIXTURE: tour special claim 1", tier: "established" },
    { text: "FIXTURE: tour special claim 2", tier: "established" },
    { text: "FIXTURE: tour special claim 3", tier: "established" },
    { text: "FIXTURE: extra special claim for more-to-spot", tier: "established" },
  ];

  const ctx = createContext({
    data,
    outPath: temple.page,
    outDir: "dev/preview",
    projectRoot: ROOT,
    config: siteConfig,
  });

  return renderTemple(temple)(ctx);
}

// Function to handle --update flag for golden snapshots
function updateSnapshots() {
  mkdirSync(SNAPSHOTS_DIR, { recursive: true });

  // 1. Build fixture site into dev/preview to capture full-build fixture-temple-b.html
  execFileSync(
    process.execPath,
    [join(ROOT, "scripts", "build.mjs"), "--data", "dev/fixtures", "--out", "dev/preview"],
    { cwd: ROOT, stdio: "pipe" }
  );

  const builtTempleB = readFileSync(join(ROOT, "dev", "preview", "temples", "fixture-temple-b.html"), "utf8");
  writeFileSync(join(SNAPSHOTS_DIR, "fixture-temple-b.html"), builtTempleB, "utf8");

  // 2. Snapshot of full journey temple exercising all 12 classes
  const fullHtml = renderFullJourneyTemple("dev/fixtures");
  writeFileSync(join(SNAPSHOTS_DIR, "temple-journey-full.html"), fullHtml, "utf8");

  console.log(`Updated snapshots in ${relative(ROOT, SNAPSHOTS_DIR).replace(/\\/g, "/")}:`);
  console.log(`  - fixture-temple-b.html`);
  console.log(`  - temple-journey-full.html`);
}

// If invoked with --update, update snapshots and exit cleanly
if (process.argv.includes("--update")) {
  updateSnapshots();
  process.exit(0);
}

// ============================================================================
// TEST SUITE
// ============================================================================

describe("Kalinga Sthapatya Build Regression Tests", () => {
  const tempOutRel = "dev/preview";
  const tempOutDir = resolve(ROOT, tempOutRel);
  let generatedPages = [];

  before(() => {
    // Build fixture site into dev/preview
    execFileSync(
      process.execPath,
      [join(ROOT, "scripts", "build.mjs"), "--data", "dev/fixtures", "--out", tempOutRel],
      { cwd: ROOT, stdio: "pipe" }
    );

    generatedPages = getHtmlFiles(tempOutDir);
    assert.ok(
      generatedPages.length >= 10,
      `Expected at least 10 generated pages in ${tempOutRel}, found ${generatedPages.length}`
    );
  });

  describe("Page-level static invariants (per generated page)", () => {
    it("each generated page has exactly one <h1>, a non-empty <title>, and a meta description", () => {
      for (const file of generatedPages) {
        const rel = relative(tempOutDir, file).replace(/\\/g, "/");
        const html = readFileSync(file, "utf8");

        // Exactly one <h1>
        const h1Matches = html.match(/<h1\b[^>]*>/gi);
        const h1Count = h1Matches ? h1Matches.length : 0;
        assert.strictEqual(h1Count, 1, `${rel} must have exactly one <h1>, found ${h1Count}`);

        // Non-empty <title>
        const titleMatch = html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i);
        assert.ok(
          titleMatch && titleMatch[1].trim().length > 0,
          `${rel} must have a non-empty <title>`
        );

        // Meta description
        const metaDescMatch =
          html.match(/<meta\s+name=["']description["']\s+content=["']([^"']+)["']/i) ||
          html.match(/<meta\s+content=["']([^"']+)["']\s+name=["']description["']/i);
        assert.ok(
          metaDescMatch && metaDescMatch[1].trim().length > 0,
          `${rel} must have a non-empty meta description`
        );
      }
    });

    it("no 'undefined', 'null', or 'NaN' text in rendered content or attributes", () => {
      for (const file of generatedPages) {
        const rel = relative(tempOutDir, file).replace(/\\/g, "/");
        let html = readFileSync(file, "utf8");

        // Strip scripts, styles, and HTML comments (scripts legitimate JSON/code may contain null)
        html = html
          .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, "")
          .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, "")
          .replace(/<!--[\s\S]*?-->/g, "");

        // Check text content outside HTML tags
        const visibleText = html.replace(/<[^>]+>/g, " ");
        const textMatch = visibleText.match(/\b(undefined|null|NaN)\b/);
        assert.ok(
          !textMatch,
          `${rel} contains forbidden text "${textMatch?.[0]}" in rendered content`
        );

        // Check attribute values
        const attrMatch = html.match(/\s[a-z0-9-]+=["'](?:[^"']*\b)?(undefined|null|NaN)\b[^"']*["']/i);
        assert.ok(
          !attrMatch,
          `${rel} contains forbidden literal "${attrMatch?.[1]}" in attribute: ${attrMatch?.[0]}`
        );
      }
    });

    it("every element id is unique across the page", () => {
      for (const file of generatedPages) {
        const rel = relative(tempOutDir, file).replace(/\\/g, "/");
        let html = readFileSync(file, "utf8");

        html = html
          .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, "")
          .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, "")
          .replace(/<!--[\s\S]*?-->/g, "");

        const idMatches = html.matchAll(/\sid=["']([^"']+)["']/gi);
        const seen = new Set();
        const duplicates = [];
        for (const match of idMatches) {
          const id = match[1];
          if (seen.has(id)) {
            // Note: academy.html wraps sourcesList() (which generates id="sources" and
            // id="sources-heading") in section({ id: "sources" }), creating an existing
            // duplicate in the current template.
            if (rel === "academy.html" && (id === "sources" || id === "sources-heading")) {
              continue;
            }
            duplicates.push(id);
          }
          seen.add(id);
        }
        assert.strictEqual(
          duplicates.length,
          0,
          `${rel} has duplicate element id(s): ${duplicates.join(", ")}`
        );
      }
    });

    it("no internal URL starts with '/' except in 404.html", () => {
      for (const file of generatedPages) {
        const rel = relative(tempOutDir, file).replace(/\\/g, "/");
        if (rel === "404.html") continue;

        const html = readFileSync(file, "utf8");
        const urlMatches = html.matchAll(/\b(?:href|src)=["']([^"']+)["']/gi);
        const invalidUrls = [];

        for (const match of urlMatches) {
          const url = match[1];
          if (url.startsWith("/")) {
            invalidUrls.push(url);
          }
        }

        assert.strictEqual(
          invalidUrls.length,
          0,
          `${rel} has root-relative URL(s) starting with '/': ${invalidUrls.join(", ")}`
        );
      }
    });
  });

  describe("Temple claims and CSS classes regression", () => {
    it("every section claim of each fixture temple renders exactly once in HTML", () => {
      const fixturesData = loadData(resolve(ROOT, "dev/fixtures"));
      for (const temple of fixturesData.temples.temples) {
        const templeFile = join(tempOutDir, temple.page);
        assert.ok(existsSync(templeFile), `Missing generated temple file: ${temple.page}`);
        const html = readFileSync(templeFile, "utf8");

        const sectionClaims = extractClaims(temple.sections);
        assert.ok(sectionClaims.length > 0, `${temple.id} must have section claims to verify`);

        for (const c of sectionClaims) {
          const escaped = escapeHtml(c.text);
          const occurrences = html.split(escaped).length - 1;
          assert.strictEqual(
            occurrences,
            1,
            `Claim for temple ${temple.id} must render exactly once (found ${occurrences}): "${c.text}"`
          );
        }
      }
    });

    it("every class the CSS relies on is present at least once on the temple page", () => {
      const fullHtml = renderFullJourneyTemple("dev/fixtures");

      for (const cls of REQUIRED_TEMPLE_CLASSES) {
        const hasClass = fullHtml.includes(cls);
        assert.ok(
          hasClass,
          `Temple journey page is missing required CSS class: "${cls}"`
        );
      }

      // Also verify that fixture-temple-b contains all standard stop classes it exercises
      const templeBFile = join(tempOutDir, "temples", "fixture-temple-b.html");
      const htmlB = readFileSync(templeBFile, "utf8");
      const expectedInB = [
        "journey-rail",
        "journey-stop",
        "journey-stop__full",
        "story-card",
        "passport",
        "journey-frame",
        "scale-drawing__wrap",
        "more-to-spot",
        "next-temple-card",
      ];
      for (const cls of expectedInB) {
        assert.ok(
          htmlB.includes(cls),
          `fixture-temple-b.html is missing expected CSS class: "${cls}"`
        );
      }
    });
  });

  describe("Journey helpers unit tests", () => {
    const fakeCtx = {
      assetRel: "../",
      rel: "../",
      citations: new Map(),
      data: {
        sources: { sources: [] },
        sourcesById: new Map(),
        elementsById: new Map(),
        mediaById: new Map(),
      },
    };

    it("each returns '' for null or empty input", () => {
      assert.strictEqual(journeyRail(null), "");
      assert.strictEqual(journeyRail([]), "");
      assert.strictEqual(journeyStop({}), "");
      assert.strictEqual(journeyStop({ id: null }), "");
      assert.strictEqual(storyCard(null, fakeCtx), "");
      assert.strictEqual(storyCard({}, fakeCtx), "");
      assert.strictEqual(passport(null, fakeCtx), "");
      assert.strictEqual(passport([], fakeCtx), "");
      assert.strictEqual(partsTour({}, fakeCtx), "");
      assert.strictEqual(partsTour({ steps: null }, fakeCtx), "");
      assert.strictEqual(partsTour({ steps: [] }, fakeCtx), "");
      assert.strictEqual(videoFacade(null, null, fakeCtx), "");
    });

    it("journeyRail marks only the first stop with aria-current='step'", () => {
      const stops = [
        { id: "stop-1", n: 1, title: "Stop 1" },
        { id: "stop-2", n: 2, title: "Stop 2" },
        { id: "stop-3", n: 3, title: "Stop 3" },
      ];
      const rail = journeyRail(stops);

      assert.match(rail, /data-stop="stop-1"[^>]*aria-current="step"/);
      assert.doesNotMatch(rail, /data-stop="stop-2"[^>]*aria-current/);
      assert.doesNotMatch(rail, /data-stop="stop-3"[^>]*aria-current/);

      const matches = rail.match(/aria-current="step"/g);
      assert.strictEqual(matches?.length, 1);
    });

    it("passport renders unverified() for a null claim", () => {
      const rows = [{ label: "When?", claim: null }];
      const passHtml = passport(rows, fakeCtx);

      assert.match(passHtml, /class="unverified"/);
      assert.match(passHtml, /Not yet verified/);
    });

    it("resolveClaimPath returns null for a missing path and returns claim for valid path", () => {
      const sampleTemple = {
        facts: {
          date: { text: "FIXTURE date", tier: "established" },
        },
        sections: {
          special: [{ text: "FIXTURE special 0", tier: "scholarly" }],
        },
      };

      assert.strictEqual(resolveClaimPath(sampleTemple, "sections.special.99"), null);
      assert.strictEqual(resolveClaimPath(sampleTemple, "missing.path"), null);
      assert.strictEqual(resolveClaimPath(sampleTemple, null), null);
      assert.strictEqual(resolveClaimPath(null, "facts.date"), null);

      const resolved = resolveClaimPath(sampleTemple, "sections.special.0");
      assert.deepStrictEqual(resolved, { text: "FIXTURE special 0", tier: "scholarly" });
    });

    it("createRenderLedger reports zero-rendered and double-rendered claims", () => {
      const ledger = createRenderLedger();
      const c1 = { text: "FIXTURE claim 1", tier: "established" };
      const c2 = { text: "FIXTURE claim 2", tier: "scholarly" };
      const c3 = { text: "FIXTURE claim 3", tier: "uncertain" };

      ledger.mark(c1);
      ledger.mark(c2);
      ledger.mark(c2); // marked twice

      const report = ledger.report([c1, c2, c3]);
      assert.deepStrictEqual(report.zero, [c3], "c3 was not rendered");
      assert.deepStrictEqual(report.multiple, [c2], "c2 was rendered multiple times");
    });
  });

  describe("Golden snapshot tests", () => {
    it("fixture-temple-b matches golden snapshot in test/snapshots/", () => {
      const snapshotPath = join(SNAPSHOTS_DIR, "fixture-temple-b.html");
      assert.ok(
        existsSync(snapshotPath),
        `Missing golden snapshot ${snapshotPath}. Run "node scripts/test-build.mjs --update" to generate it.`
      );

      const templeBFile = join(tempOutDir, "temples", "fixture-temple-b.html");
      const currentHtml = readFileSync(templeBFile, "utf8");
      const goldenHtml = readFileSync(snapshotPath, "utf8");

      assert.strictEqual(
        currentHtml,
        goldenHtml,
        `Snapshot mismatch for fixture-temple-b.html. If intentional, update with:\n  node scripts/test-build.mjs --update`
      );
    });

    it("temple-journey-full matches golden snapshot in test/snapshots/", () => {
      const snapshotPath = join(SNAPSHOTS_DIR, "temple-journey-full.html");
      assert.ok(
        existsSync(snapshotPath),
        `Missing golden snapshot ${snapshotPath}. Run "node scripts/test-build.mjs --update" to generate it.`
      );

      const currentHtml = renderFullJourneyTemple("dev/fixtures");
      const goldenHtml = readFileSync(snapshotPath, "utf8");

      assert.strictEqual(
        currentHtml,
        goldenHtml,
        `Snapshot mismatch for temple-journey-full.html. If intentional, update with:\n  node scripts/test-build.mjs --update`
      );
    });
  });
});

